spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: sample
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: kafka-msa:9092

producer:
  properties:
    topic1:
      name: rental_rent
    topic2:
      name: rental_return
    topic3:
      name: overdue_clear
    topic4:
      name: point_use

consumer:
  topic1:
    name: rental_result
  groupid:
    name: rental

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
